os: Visual Studio 2015
platform: 
  - x64
branches:
  except: 
  - gh-pages
configuration:
  - Release
#install:
# - ps: /dEngine/PreBuild.ps1
before_build: 
- ps: >-
    nuget restore
test: off # for some reason tests are trying to run in x86
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/2e28cd38320dbd979c87
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true