// Key.cs - dEngine
// Copyright (C) 2015-2016 DanDev (dandev.sco@gmail.com)
// 
// This library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// You should have received a copy of the GNU Lesser General Public
// along with this program. If not, see <http://www.gnu.org/licenses/>.

using System;

namespace dEngine
{
#pragma warning disable 1591
    [Flags]
    public enum Key : short
    {
        None,
        Unknown,
        Backspace,
        Tab,
        CapsLock,
        Enter,
        Escape,
        Space,
        Minus,
        Equals,
        NumLock,
        PrintScreen,
        ScrollLock,
        Pause,
        Insert,
        Home,
        PageUp,
        PageDown,
        Delete,
        End,
        Left,
        Right,
        Up,
        Down,
        Comma,
        FullStop,
        Slash,
        Backslash,
        Grave,
        Semicolon,
        Apostrophe,
        LeftBracket,
        RightBracket,
        LeftShift,
        RightShift,
        LeftAlt,
        RightAlt,
        LeftControl,
        RightControl,
        Win,
        Menu,
        Hash,
        Num0,
        Num1,
        Num2,
        Num3,
        Num4,
        Num5,
        Num6,
        Num7,
        Num8,
        Num9,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        ButtonX,
        ButtonY,
        ButtonA,
        ButtonB,
        ButtonL1,
        ButtonL2,
        ButtonL3,
        ButtonR1,
        ButtonR2,
        ButtonR3,
        ButtonStart,
        ButtonSelect,
        DPadLeft,
        DPadRight,
        DPadUp,
        DPadDown,
        Thumbstick1,
        Thumbstick2,
    }
#pragma warning restore 1591
}